name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install WebP.framework
      run: 'sh download.sh macOS framework macos'
    - name: Run unit tests
      run: 'xcodebuild -scheme WebPKitTests -project ./WebPKit.xcodeproj clean build test'
